NavBar.jsx and Equipe.jsx: fix router and responsive design
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-GeoCat pull request #31
Opened 2023-11-08 09:36 UTC by sdiakhate

2023-11-08 11:02 UTC, ioayoub requested changes

2023-11-08 11:02 UTC, ioayoub commented on frontend/src/main.jsx
> +import Jeu from "./pages/Jeu";
Components naming must be in english

2023-11-08 11:02 UTC, ioayoub commented on frontend/src/pages/Equipe.jsx
>  function Equipe() {
Same error for naming here

2023-11-08 11:02 UTC, ioayoub commented on frontend/src/components/team/card.css
> +@media only screen and (min-width: 768px) and (max-width: 991px) {
Remove this if not used

2023-11-08 11:20 UTC, ioayoub approved these changes

2023-11-08 11:20 UTC, ioayoub requested changes
Conflicts to fix

2023-11-09 13:22 UTC, QuentinVerwaerde requested changes

2023-11-09 13:22 UTC, QuentinVerwaerde commented on frontend/src/main.jsx
Hi, not sure to what the "Game page" refers to but if it's about the actual game, it's not necessary to specify a path for it as it should be directly loaded on the Homepage (for reference, see my recent pull request where I put <Home/> into Main.jsx and call inside Home two components :  <Hints/> and <Markers/>).
If it's simply the tutorial, please rename it as it should be.

2023-11-09 13:22 UTC, QuentinVerwaerde commented on frontend/src/pages/Game.jsx
Same comment as before, not sure what's the use for this page/component. If you could elaborate, it would be pretty useful. 
Thanks.

2023-11-09 13:45 UTC, sdiakhate commented on frontend/src/main.jsx
I respected the layout of the site. We said that the game page is to explain the game, a kind of tutorial

2023-11-09 13:47 UTC, sdiakhate commented on frontend/src/pages/Game.jsx
Look at the US and the layout of the site. You can reread the US6 if necessary

2023-11-09 19:17 UTC, QuentinVerwaerde commented on frontend/src/pages/Game.jsx
Then apply the basics of naming things after what they do. If it leads to the tutorial, name this button accordingly.
And let the user return to "path : / " by clicking on a button named either home or game, like every basic website let you do.

2023-11-09 19:17 UTC, QuentinVerwaerde commented on frontend/src/main.jsx
The layout is straight up missing a button, as there is like 4 pages and 3 boutons on it. 
A mere look would make it obvious as the tutorial page was added without any "prototype linking" to any button, by either a lack of care or time to implement it. 
You should also respect the checkout and user stories then. 

Anyway, 4 pages > 4 buttons. 
If you want a tutorial button, rename it as it.

And read for further informations
- checkout's US03 : "je peux voir une carte du monde et des marqueurs dessus en ouvrant le site"
- issue n°8 : " Créer une carte du monde et ses marqueurs sur la page d'acceuil #8 
Critère de validation :
En ouvrant le site, la page d'acceuil nous propose une carte du monde "type google map"

2023-11-09 21:06 UTC, sdiakhate commented on frontend/src/pages/Game.jsx
It’s okay I made the changes.

2023-11-10 08:45 UTC, ioayoub approved these changes

2023-11-10 09:00 UTC, QuentinVerwaerde approved these changes

2023-11-10 09:02 UTC, merged